Numpy arrays

In [2]:
import numpy as np

shape of nummpy arrays:
- rows, columns, sets


In [13]:
# 1 dimensional array 
array1 = np.array([1,2,3])
print(array1)
array1.shape

[1 2 3]


(3,)

In [21]:
# 2 dimensional array 
array2 = np.array([[1,2,3],
                   [4,5,6]])
print(array2)
print(array2.shape)
print("this array has 2 rows and 3 columns")

[[1 2 3]
 [4 5 6]]
(2, 3)
this array has 2 rows and 3 columns


In [22]:
# 2 dimensional array (another example)
array2 = np.array([[1,2],
                   [3,4],
                   [5,6]]) #innermost parentheses show COLUMNS, number of sets in next parentheses shows ROWS
print(array2)
print(array2.shape)
print("this array has 3 rows and 2 columns")

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
this array has 3 rows and 2 columns


In [23]:
# 3 dimensional array 
array3 = np.array(
    [
        [[1,2,3,4],
         [4,5,7,8]],

        [[9,10,11,12],
         [13,14,15,16]],

       [[17,18,19,20],
        [21,22,23,24]]
                        ]
)
print(array3)
print(array3.shape)
print("this array has 3 elements, 2 rows, and 4 columns")
#start with innermost set of parentheses (4 columns) then the next level of parentheses tell us we have 2 rows, and then the final set of parentheses tells us we have 3 sets/groups

[[[ 1  2  3  4]
  [ 4  5  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
(3, 2, 4)
this array has 3 elements, 2 rows, and 4 columns


In [ ]:
# 4 dimensional array
array4 = np.zeros((2, 3, 4, 6))
print(array4)
print("this array has 6 columns, 4 rows, and 3 elements, and 2 sets")

[[[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]]
this array has 6 columns, 4 rows, and 3 sets


In [ ]:
# to figure out how many dimensions our array has we can do this:

array4.ndim 

4

In [4]:
my_np_array = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(type(my_np_array))
# output: <class 'numpy.ndarray'>
print(my_np_array.shape)
# output: (2, 3)
print(my_np_array.dtype)
# output: dtype('int32')

<class 'numpy.ndarray'>
(2, 3)
int32


notation is always [row, column]
my_np_array = np.array([[row0/column0, row0/column1, row0/column2], [row1/column0, row1/column1, row1/column2]], np.int32)


my_np_array[1, 2] 

This is how we call the element of my_np_array that's in the *second* row, *third* column, namely, 6. Recall that we start at 0, so 1 repesents the 2nd row.




In [20]:
row0_col0 = my_np_array[0,0]
print(row0_col0)

row0_col1 = my_np_array[0,1]
print(row0_col1)

row0_col2 = my_np_array[0,2]
print(row0_col2)

row1_col0 = my_np_array[1,0]
print(row1_col0)

row1_col1 = my_np_array[1,1]
print(row1_col1)

row1_col2 = my_np_array[1,2]
print(row1_col2)

# row2_col1 = my_np_array[2,1]
# print(row2_col1) #this gives an index error because the array is only 2 rows wide (row 0 and row 1) so there is no row 2

1
2
3
4
5
6


for 3 dimensional arrays the notation is:

(2,4,3) = 2 elements, 4 rows, 3 columns

##### Axes are defined for arrays with more than one dimension. 
##### A 2-dimensional array has two corresponding axes: 
- the first running vertically downwards across rows (axis 0),
- and the second running horizontally across columns (axis 1).

**the axis parameter indicates which axis gets collapsed**

*note: this is NOT true for 1D arrays because they only have 1 axis so they are collapsed horizontally even though axis=0*

good article for reference: https://sharpsight.ai/blog/numpy-axes-explained/ 
